---
title: "Montoro et al. structure plots"
author: "Jason Willwerscheid"
date: "2/2/2025"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---

## Introduction

Here I produce structure plots for EBNMF, NMF, and topic model fits to the larger dataset from Montoro et al.

Load the Tidyverse:

```{r, message=FALSE}
library(tidyverse)
library(cowplot)
```

Load the `flashier` results:

```{r}
scale_FF <- function(FF, LL, D = 1) {
  LL_norms <- apply(LL, 2, function(x) sqrt(sum(x^2)))
  return(t(t(FF) * D * LL_norms))
}

ebnmf <- readRDS("output/montoro-ebmf.rds")
ebnmf_FF <- scale_FF(ebnmf$fit$F.pm, ebnmf$fit$L.pm)
```

Extract cell covariates:

```{r}
cell_types <- c(
      "Ciliated",
      "Proliferating",
      "Basal",
      "Club",
      "Club (hillock-associated)",
      "Goblet.progenitor",
      "Goblet.1",
      "Goblet.2",
      "Tuft.progenitor",
      "Tuft.1",
      "Tuft.2",
      "Neuroendocrine",
      "Ionocyte"
)

ct_abbr <- cell_types
ct_abbr <- str_replace(ct_abbr, "\\.", "\\-")
ct_abbr[2] <- "Prolif."
ct_abbr[5] <- "Hillock"
ct_abbr[12] <- "NEC"
ct_abbr <- str_replace(ct_abbr, "progenitor", "Pr.")

external_info <- tibble(
  CellType = sapply(strsplit(rownames(ebnmf_FF), "_"), `[[`, 5),
  TimePoint = sapply(strsplit(rownames(ebnmf_FF), "_"), `[[`, 2),
  Replicate = sapply(strsplit(rownames(ebnmf_FF), "_"), `[[`, 3)
) |>
  left_join(tibble(CellType = cell_types, CtAbbr = ct_abbr), by = "CellType") |>
  mutate(
    CellType = factor(CellType, levels = cell_types),
    CtAbbr = factor(CtAbbr, levels = ct_abbr),
    TimePoint = factor(TimePoint),
    Replicate = factor(Replicate),
  ) |>
  mutate(
    TPxRep = fct_cross(Replicate, TimePoint),
    CommonType = fct_collapse(CtAbbr, Other = ct_abbr[6:13])
  )
```

I will use the following functions to generate plots:

```{r}
make_tib <- function(FF, info_col, ksort, ncells = 50, duprate = 1) {
  info <- external_info[[info_col]]

  # Downsample the number of cells.
  set.seed(666)
  cell_idx <- numeric(0)
  for (k in levels(info)) {
    which_idx <- which(info == k)
    # Downsample common cell types. Duplicate rare ones.
    if (ncells < length(which_idx)) {
      which_idx <- sample(which_idx, ncells, replace = FALSE)
    } else if (ncells >= length(which_idx) * duprate) {
      which_idx <- rep(which_idx, duprate)
    }
    cell_idx <- c(cell_idx, which_idx)
  }

  FF <- FF[cell_idx, ]
  info <- info[cell_idx]
  colnames(FF) <- 1:ncol(FF)

  lvls <- as.numeric(ksort)
  if (any(setdiff(1:ncol(FF), ksort))) {
    lvls <- c("Other", lvls)
  }

  tib <- as_tibble(FF) |>
    mutate(
      CellIdx = row_number(),
      Info = info
    ) |>
    pivot_longer(
      -c(CellIdx, Info),
      names_to = "Component",
      values_to = "Loading",
      values_drop_na = TRUE
    ) |>
    mutate(
      Component = ifelse(as.numeric(Component) %in% ksort, Component, "Other")
    ) |>
    group_by(CellIdx, Info, Component) |>
    summarize(Loading = sum(Loading), .groups = "drop") |>
    mutate(
      Component = factor(Component, levels = lvls)
    ) |>
    arrange(Info, Component)
  
  levels(tib$Component) <- c("Other", names(ksort))

  return(tib)
}

do_plot <- function(tib, colors, ptitle, ntiles = 400) {
  struct_df <- tib |>
    pivot_wider(names_from = Component, values_from = Loading)
  Lmat <- struct_df |>
    select(-(1:2)) |>
    as.matrix()
  group <- struct_df$Info
  
  if ("Other" %in% tib$Component) {
    colors <- c("grey90", colors)
  }
  
  p <- fastTopics::structure_plot(
    Lmat, topics = colnames(Lmat),
    grouping = group,
    colors = colors,
    # embed_method = fastTopics::umap_from_topics,
    # dims = 1,
    gap = 10,
    verbose = FALSE
  ) + theme(
    axis.text.y = element_blank()
  ) + labs(
    y = "",
    title = ptitle
  )

  return(p)
}

glasbey <- function(k) {
  return(fastTopics:::glasbey()[k])
}
```

## EBNMF

In each case I manually sort and label factors.

```{r fig.height=12, fig.width=8, message=FALSE}
ebnmf_ksort <- c(
  27, 30, 26, # Sparse
  1, 8, 10, 16, # Dense
  11, 12, 2, 24, # Time points
  6, 13, 22, # Ciliated
  21, 23, 17, # Proliferating
  4, 5, 9, # Basal
  3, 15, 7, # 26, Club-Hillock
  25, 28, 29, # Goblet
  18, 19, 14, 20 # Tuft-NEC-Ionocyte
)
names(ebnmf_ksort) <- c(
  "Sprs-a", "Sprs-b", "Sprs-c",
  "Dns-a", "Dns-b", "Dns-c", "Dns-d",
  "Tp0", "Tp30", "Tp60", "R1xTp30",
  "Cil-a", "Cil-b", "Cil-c",
  "Prl-a", "Prl-b", "Prl-c",
  "Bas-a", "Bas-b", "Bas-c",
  "Cl/G-a", "Cl/G-b", "Hil",
  "Gob-a", "Gob-b", "Gob2",
  "Tuf1", "Tuf2", "Nec", "Ion"
)

sparse_title <- "Very sparse factors"
dense_title <- "Dense factors"
tp_title <- "Time point factors"
common_title <- "Prevalent cell type factors"
rare_title <- "Rare cell type factors (common cell types are downsampled)"

sparse_k <- 1:3
ebnmf_tib <- make_tib(ebnmf_FF, "CommonType", ebnmf_ksort[sparse_k], Inf, 1)
sparse_p <- do_plot(ebnmf_tib, glasbey(2:4), sparse_title)

dense_k <- 4:7
ebnmf_tib <- make_tib(ebnmf_FF, "CommonType", ebnmf_ksort[dense_k], Inf, 1)
dense_p <- do_plot(ebnmf_tib, glasbey(5:8), dense_title)

tp_k <- 8:11
ebnmf_tib <- make_tib(ebnmf_FF, "TPxRep", ebnmf_ksort[tp_k], Inf, 1)
tp_p <- do_plot(ebnmf_tib, glasbey(14:17), tp_title)

common_k <- c(12:14, 18:20, 23)
ebnmf_tib <- make_tib(ebnmf_FF, "CommonType", ebnmf_ksort[common_k], Inf, 1)
common_p <- do_plot(ebnmf_tib, glasbey(21:27), common_title)

rare_k <- c(15:17, 21:22, 24:30)
ebnmf_tib <- make_tib(ebnmf_FF, "CtAbbr", ebnmf_ksort[rare_k], 100, 3)
rare_p <- do_plot(ebnmf_tib, glasbey(32:43), rare_title)

plot_grid(common_p, rare_p, tp_p, dense_p, sparse_p,  nrow = 5, ncol = 1)
```

## NMF

```{r fig.height=10.5, fig.width=8, message=FALSE}
nnlm <- readRDS("output/montoro-nmf.rds")
nnlm_FF <- scale_FF(t(nnlm$fit$h), nnlm$fit$w, nnlm$fit$d)

nnlm_ksort <- c(
  1, 28, 10, 26, # dense
  9, 5, # time points (dense)
  3, 11, 8, 7, # time points
  21, # replicate x TP
  20, 15, 22, # ciliated
  24, 12, 19, # prolif
  2, 6, 4, 14, 13, # basal
  25, 17, 23, # club/goblet
  18, 16, # hillock
  29, # tuft
  27, # NEC
  30 # ionocyte
)
names(nnlm_ksort) <- c(
  "Dns-a", "Dns-b", "Dns-c", "Dns-d",
  "TpxCl", "Tp30/60",
  "Tp0-a", "Tp0-b", "Tp30", "Tp60",
  "R1xTp30",
  "Cil-a", "Cil-b", "Cil-c",  
  "Prl-a", "Prl-b", "Prl-c",
  "Bas-a", "Bas-b", "Bas-c", "Bas-d", "Bas-e",
  "Cl/G-a", "Cl/G-b", "Cl/G-c",
  "Hil-a", "Hil-b",
  "Tuf",
  "Nec",
  "Ion"
)

nnlm_dense_k <- 1:4
nnlm_tib <- make_tib(nnlm_FF, "CommonType", nnlm_ksort[nnlm_dense_k], Inf, 1)
nnlm_dense_p <- do_plot(nnlm_tib, glasbey(5:8), dense_title)

nnlm_tp_k <- 5:11
nnlm_tib <- make_tib(nnlm_FF, "TPxRep", nnlm_ksort[nnlm_tp_k], Inf, 1)
nnlm_tp_p <- do_plot(nnlm_tib, glasbey(11:17), tp_title)

nnlm_common_k <- c(12:14, 18:22, 26:27)
nnlm_tib <- make_tib(nnlm_FF, "CommonType", nnlm_ksort[nnlm_common_k], Inf, 1)
nnlm_common_p <- do_plot(nnlm_tib, glasbey(21:30), common_title)

nnlm_rare_k <- c(15:17, 23:25, 28:30)
nnlm_tib <- make_tib(nnlm_FF, "CtAbbr", nnlm_ksort[nnlm_rare_k], 100, 3)
nnlm_rare_p <- do_plot(nnlm_tib, glasbey(32:40), rare_title)

plot_grid(nnlm_common_p, nnlm_rare_p, nnlm_tp_p, nnlm_dense_p, nrow = 4, ncol = 1)
```

## Topic model

```{r fig.height=10.5, fig.width=8, message=FALSE}
tm <- readRDS("output/montoro-topics.rds")
tm_fit <- tm$fit
tm_fit$F <- tm$fit$L
tm_fit$L <- tm$fit$F
tm_fit$Fn <- tm$fit$Ln
tm_fit$Ln <- tm$fit$Fn
tm_fit$Fy <- tm$fit$Ly
tm_fit$Ly <- tm$fit$Fy
tm_fit <- fastTopics::poisson2multinom(tm_fit)
tm_FF <- tm_fit$L

tm_ksort <- c(
  21, 5, 11, 17, 27, # Dense  
  19, # Tp30/60xCl
  15, 8, # Tp0/60?
  24, # Tp30/60
  14, 26, # Tp0
  23, 29, 9, # Tp30 - 23 also club
  13, # Tp60
  25, # Ciliated
  6, # Proliferating
  10, 4, # Basal/Prolif
  12, # Basal
  3, # Club/Goblet
  22, # Club
  16, 28, # Hillock/Goblet-progenitor
  20, 18, # Hillock
  7, # Goblet-p/1
  2, # Goblet-2
  1, 30 # Tuft-NEC-Ion
)
names(tm_ksort) <- c(
  "Dns-a", "Dns-b", "Dns-c",
  "Dns-d", "Dns-e",
  "TpxCl",
  "Tp0/60-a", "Tp0/60-b",
  "Tp30/60",
  "Tp0-a", "Tp0-b",
  "Tp30xCl", "Tp30-a", "Tp30-b",
  "Tp60",
  "Cil",
  "Prl",
  "B/P-a", "B/P-b",
  "Bas", 
  "Cl/G", "Club",
  "H/G-a", "H/G-b", "Hil-a", "Hil-b",
  "Gob1", "Gob2",
  "TNI-a", "TNI-b"
)

tm_dense_k <- 1:5
tm_tib <- make_tib(tm_FF, "CommonType", tm_ksort[tm_dense_k], Inf, 1)
tm_dense_p <- do_plot(tm_tib, glasbey(5:9), dense_title)

tm_tp_k <- 6:15
tm_tib <- make_tib(tm_FF, "TPxRep", tm_ksort[tm_tp_k], Inf, 1)
tm_tp_p <- do_plot(tm_tib, glasbey(11:20), tp_title)

tm_common_k <- c(16, 20:22, 25:26)
tm_tib <- make_tib(tm_FF, "CommonType", tm_ksort[tm_common_k], Inf, 1)
tm_common_p <- do_plot(tm_tib, glasbey(23:29), common_title)

tm_rare_k <- c(17:19, 23:24, 27:30)
tm_tib <- make_tib(tm_FF, "CtAbbr", tm_ksort[tm_rare_k], 100, 3)
tm_rare_p <- do_plot(tm_tib, glasbey(32:40), rare_title)

plot_grid(tm_common_p, tm_rare_p, tm_tp_p, tm_dense_p, nrow = 4, ncol = 1)
```
