---
title: "Visualizations (All heatmaps)"
author: "Jason Willwerscheid"
date: "5/10/2022"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(Polychrome)
library(fastTopics)
library(cowplot)
library(ggrepel)
```

## Montoro

```{r montoro, fig.height=24, fig.width=10, warning=FALSE, message=FALSE}
nnebmf <- readRDS("./output/pulseseq-sel-nnebmf-k=30.rds")
snnebmf <- readRDS("./output/pulseseq-sel-snnebmf-k=30.rds")
nmf <- readRDS("./output/pulseseq-sel-nmf-k=30.rds")
tm <- readRDS("./output/pulseseq-sel-topics-k=30.rds")

fl <- nnebmf$fit
FF <- fl$F.pm
FF <- scale(FF, center = FALSE, scale = apply(FF, 2, max))
FF <- FF[, -1]
colnames(FF) <- paste0("k", 1:ncol(FF))

cell.type <- sapply(strsplit(rownames(FF), "_"), `[[`, 5)
cell.type <- factor(cell.type, levels = sort(unique(cell.type))[c(
  1, 4, 3, 2, 7, 5, 6, 13, 11, 12, 9, 8, 10
)])

# Downsample the number of cells and sort them using tSNE.
set.seed(666)
cell.idx <- numeric(0)
cell.types <- levels(cell.type)
for (i in 1:length(cell.types)) {
  which.idx <- which(cell.type == cell.types[i])
  # Downsample common cell types.
  if (length(which.idx) > 100) {
    which.idx <- sample(which.idx, 100)
  }
  # Don't include rare cell types.
  if (length(which.idx) > 20) {
    # Sort using tsne.
    tsne.res <- Rtsne::Rtsne(
      FF[which.idx, ],
      dims = 1,
      pca = FALSE,
      normalize = FALSE,
      perplexity = min(100, floor((length(which.idx) - 1) / 3) - 1),
      theta = 0.1,
      max_iter = 1000,
      eta = 200,
      check_duplicates = FALSE
    )$Y[, 1]
    which.idx <- which.idx[order(tsne.res)]
    cell.idx <- c(cell.idx, which.idx)
  }
}

cell.type <- cell.type[cell.idx]
cell.type <- droplevels(cell.type)

ebmf.FF <- fl$F.pm[cell.idx, ]
snn.FF <- snnebmf$fit$F.pm[cell.idx, ]
nmf.FF <- (t(nmf$fit$h))[cell.idx, ]
tm.FF <- tm$fit$F[cell.idx, ]

make.heatmap.tib <- function(FF) {
  tib <- as_tibble(scale(FF, center = FALSE, scale = apply(FF, 2, max))) %>%
    mutate(Cell.type = cell.type) %>%
    arrange(Cell.type) %>%
    mutate(Cell.idx = row_number())
  
  tib <- tib %>%
    pivot_longer(
      -c(Cell.idx, Cell.type),
      names_to = "Factor",
      values_to = "Loading",
      values_drop_na = TRUE
    ) %>%
    mutate(Factor = as.numeric(str_extract(Factor, "[0-9]+")))
  
  return(tib)
}

ebmf.tib <- make.heatmap.tib(ebmf.FF)
nmf.tib <- make.heatmap.tib(nmf.FF)
snn.tib <- make.heatmap.tib(snn.FF)
tm.tib <- make.heatmap.tib(tm.FF)

heatmap.tib <- ebmf.tib %>% mutate(Method = "NN-EBMF") %>%
  bind_rows(nmf.tib %>% mutate(Method = "NMF")) %>%
  bind_rows(snn.tib %>% mutate(Method = "SNN-EBMF")) %>%
  bind_rows(tm.tib %>% mutate(Method = "Topics")) %>%
  mutate(Method = factor(Method, levels = c("NMF", "NN-EBMF", "SNN-EBMF", "Topics")))

tib <- heatmap.tib %>%
  group_by(Cell.type, Cell.idx) %>%
  summarize()

cell_type_breaks <- c(1, which(tib$Cell.type[-1] != tib$Cell.type[-nrow(tib)]))
label_pos <- cell_type_breaks / 2 + c(cell_type_breaks[-1], nrow(tib)) / 2

plt <- ggplot(heatmap.tib, aes(x = Factor, y = -Cell.idx, fill = Loading)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "firebrick") +
  labs(y = "") +
  scale_y_continuous(breaks = -label_pos,
                     minor_breaks = NULL,
                     labels = levels(cell.type)) +
  theme_minimal() +
  geom_hline(yintercept = -cell_type_breaks, size = 0.1) +
  facet_wrap(~Method, ncol = 1) +
  theme(legend.position = "none", 
        strip.text = element_text(size = 16))

plt
```

## Pijuan-Sala

```{r pijuan, fig.height=32, fig.width=10, warning=FALSE, message=FALSE}
nnebmf <- readRDS("./output/pijuan-sel-nnebmf-k=40.rds")
snnebmf <- readRDS("./output/pijuan-sel-snnebmf-k=40.rds")
nmf <- readRDS("./output/pijuan-sel-nmf-k=40.rds")
tm <- readRDS("./output/pijuan-sel-topics-k=40.rds")

fl <- nnebmf$fit
FF <- fl$F.pm
FF <- scale(FF, center = FALSE, scale = apply(FF, 2, max))
FF <- FF[, -1]
colnames(FF) <- paste0("k", 1:ncol(FF))

# Use same cell type order as paper.
cell.type <- sapply(strsplit(rownames(FF), "_"), `[[`, 6)
cell.type <- str_replace(cell.type, "Haematoendothelial", "Haematoendo.")
cell.type <- factor(cell.type, levels = sort(unique(cell.type))[c(
  5, 11, 30, 27, 8, 19, 21, 6, 28, 33, 31, 24, 23, 4, 1, 17, 22, 20, 2, 3, 12:14,
  10, 26, 32, 7, 25, 18, 34, 36, 16, 15, 29, 37,
  9, 35
)])
tomato <- factor(sapply(strsplit(rownames(FF), "_"), `[[`, 4))

# Downsample the number of cells and sort them using tSNE.
set.seed(666)
cell.idx <- numeric(0)
cell.types <- levels(cell.type)
cell.types <- setdiff(cell.types, c("Doublet", "Stripped"))
for (i in 1:length(cell.types)) {
  which.idx <- which(cell.type == cell.types[i])
  # Downsample common cell types.
  if (length(which.idx) > 100) {
    which.idx <- sample(which.idx, 100)
  }
  # Don't include rare cell types.
  if (length(which.idx) > 20) {
    # Sort using tsne.
    tsne.res <- Rtsne::Rtsne(
      FF[which.idx, ],
      dims = 1,
      pca = FALSE,
      normalize = FALSE,
      perplexity = min(100, floor((length(which.idx) - 1) / 3) - 1),
      theta = 0.1,
      max_iter = 1000,
      eta = 200,
      check_duplicates = FALSE
    )$Y[, 1]
    which.idx <- which.idx[order(tsne.res)]
    cell.idx <- c(cell.idx, which.idx)
  }
}

cell.type <- cell.type[cell.idx]
tomato <- tomato[cell.idx]
cell.type <- droplevels(cell.type)

ebmf.FF <- fl$F.pm[cell.idx, ]
snn.FF <- snnebmf$fit$F.pm[cell.idx, ]
nmf.FF <- (t(nmf$fit$h))[cell.idx, ]
tm.FF <- tm$fit$F[cell.idx, ]

make.heatmap.tib <- function(FF) {
  tib <- as_tibble(scale(FF, center = FALSE, scale = apply(FF, 2, max))) %>%
    mutate(Cell.type = cell.type, Tomato = tomato) %>%
    arrange(Cell.type, Tomato) %>%
    mutate(Cell.idx = row_number())
  
  tib <- tib %>%
    pivot_longer(
      -c(Cell.idx, Cell.type, Tomato),
      names_to = "Factor",
      values_to = "Loading",
      values_drop_na = TRUE
    ) %>%
    mutate(Factor = as.numeric(str_extract(Factor, "[0-9]+")))
  
  return(tib)
}

ebmf.tib <- make.heatmap.tib(ebmf.FF)
nmf.tib <- make.heatmap.tib(nmf.FF)
snn.tib <- make.heatmap.tib(snn.FF)
tm.tib <- make.heatmap.tib(tm.FF)

heatmap.tib <- ebmf.tib %>% mutate(Method = "NN-EBMF") %>%
  bind_rows(nmf.tib %>% mutate(Method = "NMF")) %>%
  bind_rows(snn.tib %>% mutate(Method = "SNN-EBMF")) %>%
  bind_rows(tm.tib %>% mutate(Method = "Topics")) %>%
  mutate(Method = factor(Method, levels = c("NMF", "NN-EBMF", "SNN-EBMF", "Topics")))

tib <- heatmap.tib %>%
  group_by(Cell.type, Tomato, Cell.idx) %>%
  summarize()

cell_type_breaks <- c(1, which(tib$Cell.type[-1] != tib$Cell.type[-nrow(tib)]))
label_pos <- cell_type_breaks / 2 + c(cell_type_breaks[-1], nrow(tib)) / 2
tomato_breaks <- which(tib$Tomato[-1] != tib$Tomato[-nrow(tib)])
tomato_breaks <- setdiff(tomato_breaks, cell_type_breaks)

plt <- ggplot(heatmap.tib, aes(x = Factor, y = -Cell.idx, fill = Loading)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "firebrick") +
  labs(y = "") +
  scale_y_continuous(breaks = -label_pos,
                     minor_breaks = NULL,
                     labels = levels(cell.type)) +
  theme_minimal() +
  geom_hline(yintercept = -cell_type_breaks, size = 0.1) +
  geom_hline(yintercept = -tomato_breaks, size = 0.1, linetype = "dashed") +
  facet_wrap(~Method, ncol = 1) +
  theme(legend.position = "none", 
        strip.text = element_text(size = 16))

plt
```
